# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Experiment3.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CentalWindow(object):
    def setupUi(self, CentalWindow):
        CentalWindow.setObjectName("CentalWindow")
        CentalWindow.resize(900, 506)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(CentalWindow.sizePolicy().hasHeightForWidth())
        CentalWindow.setSizePolicy(sizePolicy)
        CentalWindow.setMinimumSize(QtCore.QSize(900, 506))
        CentalWindow.setMaximumSize(QtCore.QSize(900, 506))
        self.centralwidget = QtWidgets.QWidget(CentalWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(-10, 0, 900, 581))
        self.stackedWidget.setMaximumSize(QtCore.QSize(900, 800))
        self.stackedWidget.setObjectName("stackedWidget")
        self.infoPage = QtWidgets.QWidget()
        self.infoPage.setObjectName("infoPage")
        self.txtInfo = QtWidgets.QTextBrowser(self.infoPage)
        self.txtInfo.setGeometry(QtCore.QRect(70, 10, 801, 361))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.txtInfo.setFont(font)
        self.txtInfo.setObjectName("txtInfo")
        self.btnNext = QtWidgets.QPushButton(self.infoPage)
        self.btnNext.setEnabled(True)
        self.btnNext.setGeometry(QtCore.QRect(400, 390, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.btnNext.setFont(font)
        self.btnNext.setText("Next")
        self.btnNext.setAutoDefault(False)
        self.btnNext.setDefault(False)
        self.btnNext.setFlat(False)
        self.btnNext.setObjectName("btnNext")
        self.stackedWidget.addWidget(self.infoPage)
        self.consentPage = QtWidgets.QWidget()
        self.consentPage.setObjectName("consentPage")
        self.lblError = QtWidgets.QLabel(self.consentPage)
        self.lblError.setGeometry(QtCore.QRect(510, 380, 300, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lblError.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.lblError.setFont(font)
        self.lblError.setObjectName("lblError")
        self.btnContinue = QtWidgets.QPushButton(self.consentPage)
        self.btnContinue.setGeometry(QtCore.QRect(310, 380, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.btnContinue.setFont(font)
        self.btnContinue.setObjectName("btnContinue")
        self.lbl7 = QtWidgets.QLabel(self.consentPage)
        self.lbl7.setGeometry(QtCore.QRect(70, 260, 711, 35))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.lbl7.setFont(font)
        self.lbl7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lbl7.setWordWrap(True)
        self.lbl7.setObjectName("lbl7")
        self.check4 = QtWidgets.QCheckBox(self.consentPage)
        self.check4.setGeometry(QtCore.QRect(50, 190, 21, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.check4.setFont(font)
        self.check4.setText("")
        self.check4.setObjectName("check4")
        self.lbl9 = QtWidgets.QLabel(self.consentPage)
        self.lbl9.setGeometry(QtCore.QRect(70, 330, 711, 15))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl9.setFont(font)
        self.lbl9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lbl9.setWordWrap(True)
        self.lbl9.setObjectName("lbl9")
        self.check6 = QtWidgets.QCheckBox(self.consentPage)
        self.check6.setGeometry(QtCore.QRect(50, 260, 21, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.check6.setFont(font)
        self.check6.setText("")
        self.check6.setObjectName("check6")
        self.check3 = QtWidgets.QCheckBox(self.consentPage)
        self.check3.setGeometry(QtCore.QRect(50, 140, 21, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.check3.setFont(font)
        self.check3.setText("")
        self.check3.setObjectName("check3")
        self.lbl1 = QtWidgets.QLabel(self.consentPage)
        self.lbl1.setGeometry(QtCore.QRect(50, 0, 641, 55))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.lbl1.setFont(font)
        self.lbl1.setWordWrap(True)
        self.lbl1.setObjectName("lbl1")
        self.lbl6 = QtWidgets.QLabel(self.consentPage)
        self.lbl6.setGeometry(QtCore.QRect(70, 230, 711, 15))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.lbl6.setFont(font)
        self.lbl6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lbl6.setWordWrap(True)
        self.lbl6.setObjectName("lbl6")
        self.check7 = QtWidgets.QCheckBox(self.consentPage)
        self.check7.setGeometry(QtCore.QRect(50, 300, 21, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.check7.setFont(font)
        self.check7.setText("")
        self.check7.setObjectName("check7")
        self.check5 = QtWidgets.QCheckBox(self.consentPage)
        self.check5.setGeometry(QtCore.QRect(50, 230, 21, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.check5.setFont(font)
        self.check5.setText("")
        self.check5.setObjectName("check5")
        self.check2 = QtWidgets.QCheckBox(self.consentPage)
        self.check2.setGeometry(QtCore.QRect(50, 100, 21, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.check2.setFont(font)
        self.check2.setText("")
        self.check2.setObjectName("check2")
        self.lbl3 = QtWidgets.QLabel(self.consentPage)
        self.lbl3.setGeometry(QtCore.QRect(70, 100, 711, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.lbl3.setFont(font)
        self.lbl3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lbl3.setWordWrap(True)
        self.lbl3.setObjectName("lbl3")
        self.lbl5 = QtWidgets.QLabel(self.consentPage)
        self.lbl5.setGeometry(QtCore.QRect(70, 190, 711, 35))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.lbl5.setFont(font)
        self.lbl5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lbl5.setWordWrap(True)
        self.lbl5.setObjectName("lbl5")
        self.lbl8 = QtWidgets.QLabel(self.consentPage)
        self.lbl8.setGeometry(QtCore.QRect(70, 300, 711, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.lbl8.setFont(font)
        self.lbl8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lbl8.setWordWrap(True)
        self.lbl8.setObjectName("lbl8")
        self.lbl2 = QtWidgets.QLabel(self.consentPage)
        self.lbl2.setGeometry(QtCore.QRect(70, 60, 711, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setItalic(True)
        self.lbl2.setFont(font)
        self.lbl2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lbl2.setWordWrap(True)
        self.lbl2.setObjectName("lbl2")
        self.check1 = QtWidgets.QCheckBox(self.consentPage)
        self.check1.setGeometry(QtCore.QRect(50, 60, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setItalic(True)
        self.check1.setFont(font)
        self.check1.setText("")
        self.check1.setObjectName("check1")
        self.check8 = QtWidgets.QCheckBox(self.consentPage)
        self.check8.setGeometry(QtCore.QRect(50, 330, 21, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.check8.setFont(font)
        self.check8.setText("")
        self.check8.setObjectName("check8")
        self.lbl4 = QtWidgets.QLabel(self.consentPage)
        self.lbl4.setGeometry(QtCore.QRect(70, 140, 711, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.lbl4.setFont(font)
        self.lbl4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lbl4.setWordWrap(True)
        self.lbl4.setObjectName("lbl4")
        self.stackedWidget.addWidget(self.consentPage)
        self.demoPage = QtWidgets.QWidget()
        self.demoPage.setObjectName("demoPage")
        self.lbAge = QtWidgets.QLabel(self.demoPage)
        self.lbAge.setGeometry(QtCore.QRect(70, 130, 47, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbAge.setFont(font)
        self.lbAge.setObjectName("lbAge")
        self.lblErrorName = QtWidgets.QLabel(self.demoPage)
        self.lblErrorName.setGeometry(QtCore.QRect(550, 60, 141, 50))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lblErrorName.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.lblErrorName.setFont(font)
        self.lblErrorName.setWordWrap(True)
        self.lblErrorName.setObjectName("lblErrorName")
        self.boxAge = QtWidgets.QSpinBox(self.demoPage)
        self.boxAge.setGeometry(QtCore.QRect(200, 130, 42, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.boxAge.setFont(font)
        self.boxAge.setObjectName("boxAge")
        self.widGender = QtWidgets.QWidget(self.demoPage)
        self.widGender.setGeometry(QtCore.QRect(55, 170, 281, 130))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.widGender.setFont(font)
        self.widGender.setObjectName("widGender")
        self.lblGender = QtWidgets.QLabel(self.widGender)
        self.lblGender.setGeometry(QtCore.QRect(15, 30, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblGender.setFont(font)
        self.lblGender.setObjectName("lblGender")
        self.rbGender_2 = QtWidgets.QRadioButton(self.widGender)
        self.rbGender_2.setGeometry(QtCore.QRect(150, 90, 82, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.rbGender_2.setFont(font)
        self.rbGender_2.setObjectName("rbGender_2")
        self.rbGender_3 = QtWidgets.QRadioButton(self.widGender)
        self.rbGender_3.setGeometry(QtCore.QRect(150, 60, 82, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.rbGender_3.setFont(font)
        self.rbGender_3.setObjectName("rbGender_3")
        self.rbGender = QtWidgets.QRadioButton(self.widGender)
        self.rbGender.setGeometry(QtCore.QRect(150, 30, 82, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.rbGender.setFont(font)
        self.rbGender.setObjectName("rbGender")
        self.lblHeader = QtWidgets.QLabel(self.demoPage)
        self.lblHeader.setGeometry(QtCore.QRect(120, 10, 391, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.lblHeader.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblHeader.setFont(font)
        self.lblHeader.setAutoFillBackground(True)
        self.lblHeader.setAlignment(QtCore.Qt.AlignCenter)
        self.lblHeader.setWordWrap(True)
        self.lblHeader.setObjectName("lblHeader")
        self.dropEducation = QtWidgets.QComboBox(self.demoPage)
        self.dropEducation.setGeometry(QtCore.QRect(200, 330, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.dropEducation.setFont(font)
        self.dropEducation.setCurrentText("")
        self.dropEducation.setObjectName("dropEducation")
        self.dropEducation.addItem("")
        self.dropEducation.setItemText(0, "")
        self.dropEducation.addItem("")
        self.dropEducation.addItem("")
        self.dropEducation.addItem("")
        self.dropEducation.addItem("")
        self.dropEducation.addItem("")
        self.lblErrorGender = QtWidgets.QLabel(self.demoPage)
        self.lblErrorGender.setGeometry(QtCore.QRect(550, 170, 201, 130))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lblErrorGender.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.lblErrorGender.setFont(font)
        self.lblErrorGender.setWordWrap(True)
        self.lblErrorGender.setObjectName("lblErrorGender")
        self.lblErrorAge = QtWidgets.QLabel(self.demoPage)
        self.lblErrorAge.setGeometry(QtCore.QRect(550, 120, 171, 40))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lblErrorAge.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.lblErrorAge.setFont(font)
        self.lblErrorAge.setWordWrap(True)
        self.lblErrorAge.setObjectName("lblErrorAge")
        self.txtname = QtWidgets.QLineEdit(self.demoPage)
        self.txtname.setGeometry(QtCore.QRect(200, 80, 311, 19))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.txtname.setFont(font)
        self.txtname.setObjectName("txtname")
        self.lbName = QtWidgets.QLabel(self.demoPage)
        self.lbName.setGeometry(QtCore.QRect(70, 80, 91, 15))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbName.setFont(font)
        self.lbName.setObjectName("lbName")
        self.btnSubmit = QtWidgets.QPushButton(self.demoPage)
        self.btnSubmit.setGeometry(QtCore.QRect(340, 390, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.btnSubmit.setFont(font)
        self.btnSubmit.setObjectName("btnSubmit")
        self.lbEdu = QtWidgets.QLabel(self.demoPage)
        self.lbEdu.setGeometry(QtCore.QRect(70, 330, 71, 15))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbEdu.setFont(font)
        self.lbEdu.setObjectName("lbEdu")
        self.lblErrorEdu = QtWidgets.QLabel(self.demoPage)
        self.lblErrorEdu.setGeometry(QtCore.QRect(550, 310, 181, 60))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.lblErrorEdu.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.lblErrorEdu.setFont(font)
        self.lblErrorEdu.setWordWrap(True)
        self.lblErrorEdu.setObjectName("lblErrorEdu")
        self.stackedWidget.addWidget(self.demoPage)
        self.instructionsPage = QtWidgets.QWidget()
        self.instructionsPage.setObjectName("instructionsPage")
        self.lblPlayerImg = QtWidgets.QLabel(self.instructionsPage)
        self.lblPlayerImg.setGeometry(QtCore.QRect(180, 230, 41, 61))
        self.lblPlayerImg.setText("")
        self.lblPlayerImg.setPixmap(QtGui.QPixmap("img/player.png"))
        self.lblPlayerImg.setObjectName("lblPlayerImg")
        self.lblPlayer = QtWidgets.QLabel(self.instructionsPage)
        self.lblPlayer.setGeometry(QtCore.QRect(170, 170, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.lblPlayer.setFont(font)
        self.lblPlayer.setObjectName("lblPlayer")
        self.lblWASD = QtWidgets.QLabel(self.instructionsPage)
        self.lblWASD.setGeometry(QtCore.QRect(330, 170, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.lblWASD.setFont(font)
        self.lblWASD.setAlignment(QtCore.Qt.AlignCenter)
        self.lblWASD.setWordWrap(True)
        self.lblWASD.setObjectName("lblWASD")
        self.lblExplanation = QtWidgets.QLabel(self.instructionsPage)
        self.lblExplanation.setGeometry(QtCore.QRect(170, 70, 601, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.lblExplanation.setFont(font)
        self.lblExplanation.setAlignment(QtCore.Qt.AlignCenter)
        self.lblExplanation.setWordWrap(True)
        self.lblExplanation.setObjectName("lblExplanation")
        self.lblWASDImg = QtWidgets.QLabel(self.instructionsPage)
        self.lblWASDImg.setGeometry(QtCore.QRect(410, 220, 111, 71))
        self.lblWASDImg.setText("")
        self.lblWASDImg.setPixmap(QtGui.QPixmap("img/WASD2.png"))
        self.lblWASDImg.setScaledContents(True)
        self.lblWASDImg.setObjectName("lblWASDImg")
        self.lblEImg = QtWidgets.QLabel(self.instructionsPage)
        self.lblEImg.setGeometry(QtCore.QRect(690, 250, 41, 41))
        self.lblEImg.setText("")
        self.lblEImg.setPixmap(QtGui.QPixmap("img/e.png"))
        self.lblEImg.setScaledContents(True)
        self.lblEImg.setObjectName("lblEImg")
        self.lblE = QtWidgets.QLabel(self.instructionsPage)
        self.lblE.setGeometry(QtCore.QRect(640, 170, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.lblE.setFont(font)
        self.lblE.setAlignment(QtCore.Qt.AlignCenter)
        self.lblE.setWordWrap(True)
        self.lblE.setObjectName("lblE")
        self.btnUnderstand = QtWidgets.QPushButton(self.instructionsPage)
        self.btnUnderstand.setGeometry(QtCore.QRect(400, 360, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.btnUnderstand.setFont(font)
        self.btnUnderstand.setObjectName("btnUnderstand")
        self.stackedWidget.addWidget(self.instructionsPage)
        self.disclaimerPage = QtWidgets.QWidget()
        self.disclaimerPage.setObjectName("disclaimerPage")
        self.lbldisclaimer = QtWidgets.QLabel(self.disclaimerPage)
        self.lbldisclaimer.setGeometry(QtCore.QRect(180, 90, 581, 171))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.lbldisclaimer.setFont(font)
        self.lbldisclaimer.setWordWrap(True)
        self.lbldisclaimer.setObjectName("lbldisclaimer")
        self.lblRunGame = QtWidgets.QLabel(self.disclaimerPage)
        self.lblRunGame.setGeometry(QtCore.QRect(180, 310, 551, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.lblRunGame.setFont(font)
        self.lblRunGame.setAlignment(QtCore.Qt.AlignCenter)
        self.lblRunGame.setWordWrap(True)
        self.lblRunGame.setObjectName("lblRunGame")
        self.label = QtWidgets.QLabel(self.disclaimerPage)
        self.label.setGeometry(QtCore.QRect(410, 40, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.stackedWidget.addWidget(self.disclaimerPage)
        CentalWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CentalWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 20))
        self.menubar.setObjectName("menubar")
        CentalWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CentalWindow)
        self.statusbar.setObjectName("statusbar")
        CentalWindow.setStatusBar(self.statusbar)

        self.retranslateUi(CentalWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.dropEducation.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(CentalWindow)

    def retranslateUi(self, CentalWindow):
        _translate = QtCore.QCoreApplication.translate
        CentalWindow.setWindowTitle(_translate("CentalWindow", "Information Page"))
        self.txtInfo.setHtml(_translate("CentalWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:8.1pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:20px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:110%;\"><a name=\"questionnaire\"></a><span style=\" font-family:\'inherit\'; font-size:11pt; font-weight:496; color:#000000;\">I</span><span style=\" font-family:\'inherit\'; font-size:11pt; font-weight:496; color:#000000;\">nformation Sheet</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Open Sans,sans-serif\'; font-size:11pt; font-weight:600; color:#000000;\">Title of Study:</span><span style=\" font-family:\'Open Sans,sans-serif\'; font-size:11pt; color:#000000;\"> </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:11pt;\">User experiences in video games.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Open Sans,sans-serif\'; font-size:11pt; color:#000000;\">Thank you for considering taking part in this research. Please read the following information before you consent to take part in the study. If you have any questions arising from the Information Sheet or explanation already given to you, please ask the researcher before you decide whether to join in.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"q1\"></a><span style=\" font-family:\'Open Sans,sans-serif\'; font-size:11pt; font-weight:600; color:#000000;\">N</span><span style=\" font-family:\'Open Sans,sans-serif\'; font-size:11pt; font-weight:600; color:#000000;\">ame and Contact Details of the Investigators:</span></p>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" font-family:\'Open Sans,sans-serif\'; font-size:11pt; color:#000000;\" style=\" margin-top:0px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14px; font-weight:600;\">Researcher</span><span style=\" font-size:14px;\">: Agent E. Hunt, (</span><span style=\" font-size:14px; color:#e61234; background-color:transparent;\"> [redacted]@IMF.gov </span><span style=\" font-size:14px;\">)</span></li>\n"
"<li style=\" font-family:\'Open Sans,sans-serif\'; font-size:11pt; color:#000000;\" style=\" margin-top:0px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14px; font-weight:600;\">Principle Researcher</span><span style=\" font-size:14px;\">: Agent J. Bond, (</span><span style=\" font-size:14px; color:#e61234; background-color:transparent;\"> [redacted]@MI7.gov </span><span style=\" font-size:14px;\">)</span></li></ul>\n"
"<p style=\" margin-top:0px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"q2\"></a><span style=\" font-family:\'Open Sans,sans-serif\'; font-size:11pt; font-weight:600; color:#000000;\">P</span><span style=\" font-family:\'Open Sans,sans-serif\'; font-size:11pt; font-weight:600; color:#000000;\">roject’s purpose?</span><span style=\" font-family:\'Open Sans,sans-serif\'; font-size:11pt; color:#000000;\"> We aim to investigate the behaviour of participants when exploring artificial environment such as a video game. The study will take between 10-15 min. You will not be debriefed, as this would compromise our respective identities.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Open Sans,sans-serif\'; font-size:11pt; font-weight:600; color:#000000;\">Why have I been chosen?</span><span style=\" font-family:\'Open Sans,sans-serif\'; font-size:11pt; color:#000000;\"> We are targeting undercover spies such as yourself for this project specifically. However, do not be alarmed. All information about your location, allegiances, financial situation and romantic affairs will remain secure in our databases at basement of a building in an undisclosed location.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Open Sans,sans-serif\'; font-size:11pt; font-weight:600; color:#000000;\">Do I have to take part?</span><span style=\" font-family:\'Open Sans,sans-serif\'; font-size:11pt; color:#000000;\"> It is up to you to decide whether or not to take part. You can withdraw at any time without giving a reason and without it affecting any benefits that you are entitled to. However, this will make us very sad and you would miss out on some very fun minutes of your life. It may also be taken account in your yearly review and could reflect badly on your impecable track record of successful missions.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Open Sans,sans-serif\'; font-size:11pt; font-weight:600; color:#000000;\">What are the possible benefits of taking part?</span><span style=\" font-family:\'Open Sans,sans-serif\'; font-size:11pt; color:#000000;\"> We hope that this work will provide further insight into understanding the process of navigation and field behaviour in spies, undercover agents and minimum wage finance interns specifically.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Open Sans,sans-serif\'; font-size:11pt; font-weight:600; color:#000000;\">Will my taking part in this project be kept confidential?</span><span style=\" font-family:\'Open Sans,sans-serif\'; font-size:11pt; color:#000000;\"> All the information that we collect about you during the course of the research will be kept strictly confidential by means of the appropriate top-of-the-line security. This means retinal scans, gait analysis, voice recognition, DNA testing and more are in place. You will </span><span style=\" font-family:\'Open Sans,sans-serif\'; font-size:11pt; font-style:italic; color:#000000;\">not</span><span style=\" font-family:\'Open Sans,sans-serif\'; font-size:11pt; color:#000000;\"> be able to be identified in any ensuing reports or publications, neither as yourself or any of your aliases. Your data might be used for subsequent research.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Open Sans,sans-serif\'; font-size:11pt; font-weight:600; color:#000000;\">Data Protection Privacy Notice:</span><span style=\" font-family:\'Open Sans,sans-serif\'; font-size:11pt; color:#000000;\"> The data controller for this project will not be made public and cannot be contacted. We ask for your understanding in this matter.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Open Sans,sans-serif\'; font-size:11pt; color:#000000;\">Your personal data will be processed for the purposes outlined in this notice. The legal basis used to process special category personal data will be for scientific,  governmental, bureaucratical, and grammatical research.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Open Sans,sans-serif\'; font-size:11pt; color:#000000;\">If you are concerned about how your personal data is being processed, you shouldn\'t have become a top-secret spy in service of the government. This one is on you. If you remain unsatisfied, we suggest you finally cash to huge paychecks you\'ve been getting and take a life-long vacation to some remote tropical island.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Open Sans,sans-serif\'; font-size:11pt; color:#000000;\">As this is a solo mission, you will not be able or allowed to select any team members. As always, should you or any member of your team be caught or killed, the secretary will disavow all knowledge of your actions. <br />This message will self-destruct in five minutes.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Open Sans,sans-serif\'; font-size:11pt; color:#000000;\">Click </span><span style=\" font-family:\'Open Sans,sans-serif\'; font-size:11pt; font-weight:600; color:#000000;\">Next</span><span style=\" font-family:\'Open Sans,sans-serif\'; font-size:11pt; color:#000000;\"> to accept this mission.</span></p></body></html>"))
        self.lblError.setText(_translate("CentalWindow", "I am placeholder text and shouldn\'t be visible."))
        self.btnContinue.setText(_translate("CentalWindow", "Continue"))
        self.lbl7.setText(_translate("CentalWindow", "I agree that my anonymised research data may be used by others for future research. No one will be able to identify you when this data is shared."))
        self.lbl9.setText(_translate("CentalWindow", "I confirm that I understand that by ticking this box I am consenting to taking part in the study."))
        self.lbl1.setText(_translate("CentalWindow", "This study has been approved by several undisclosed secret govenment agencies. \n"
"Project ID number: MIP007\n"
"You may want to print this Consent Form to keep for your records. "))
        self.lbl6.setText(_translate("CentalWindow", "I understand that I will not benefit financially from this study or from any possible outcome it may result in the future."))
        self.lbl3.setText(_translate("CentalWindow", "I confirm that I have read and understood the Information Sheet for the above study. I have had an opportunity to consider the information and what will be expected of me."))
        self.lbl5.setText(_translate("CentalWindow", "I understand that the data will not be made available to any commercial organisations but is solely the responsibility of the researcher(s) undertaking this study."))
        self.lbl8.setText(_translate("CentalWindow", "I am aware of who I should contact if I wish to lodge a complaint."))
        self.lbl2.setText(_translate("CentalWindow", "I confirm that I understand that by ticking the box below I am consenting to the statements below. I understand that by not giving consent for any one statements that I will be deemed ineligible for the study."))
        self.lbl4.setText(_translate("CentalWindow", "I consent to participate in the study. I understand that according to data protection legislation, performance of a task in the public interest’ will be the lawful basis for processing."))
        self.lbAge.setText(_translate("CentalWindow", "Age"))
        self.lblErrorName.setText(_translate("CentalWindow", "TextLabel"))
        self.lblGender.setText(_translate("CentalWindow", "Gender"))
        self.rbGender_2.setText(_translate("CentalWindow", "Other"))
        self.rbGender_3.setText(_translate("CentalWindow", "Female"))
        self.rbGender.setText(_translate("CentalWindow", "Male"))
        self.lblHeader.setText(_translate("CentalWindow", "Please provide the following information:"))
        self.dropEducation.setItemText(1, _translate("CentalWindow", "Elementary School"))
        self.dropEducation.setItemText(2, _translate("CentalWindow", "Secondary School"))
        self.dropEducation.setItemText(3, _translate("CentalWindow", "Bachelor\'s Degree"))
        self.dropEducation.setItemText(4, _translate("CentalWindow", "Master\'s Degree"))
        self.dropEducation.setItemText(5, _translate("CentalWindow", "Doctorate"))
        self.lblErrorGender.setText(_translate("CentalWindow", "TextLabel"))
        self.lblErrorAge.setText(_translate("CentalWindow", "TextLabel"))
        self.lbName.setText(_translate("CentalWindow", "Name or Alias"))
        self.btnSubmit.setText(_translate("CentalWindow", "Submit"))
        self.lbEdu.setText(_translate("CentalWindow", "Education"))
        self.lblErrorEdu.setText(_translate("CentalWindow", "TextLabel"))
        self.lblPlayer.setText(_translate("CentalWindow", "This is you."))
        self.lblWASD.setText(_translate("CentalWindow", "You move using the W, A, S and D keys on your keyboard."))
        self.lblExplanation.setText(_translate("CentalWindow", "You are going to play a video game in which you will interact with the environment and other characters."))
        self.lblE.setText(_translate("CentalWindow", "You interact/confirm with the E key."))
        self.btnUnderstand.setText(_translate("CentalWindow", "I understand."))
        self.lbldisclaimer.setText(_translate("CentalWindow", "The story, all names, characters, and incidents portrayed in this production are fictitious. No identification with actual persons (living or deceased), places, buildings, and products is intended or should be inferred. No person or entity associated with this game received payment or anything of value, or entered into any agreement, in connection with the depiction of tobacco products. In fact, no person or entity associated with this game received any payment. No animals were harmed in the making of this game. \n"
" \n"
"All images in this game are covered under Fair Use for research purposes. Please don\'t sue me, Nintendo, I\'m just a poor student. :\'( \n"
"(But also pls hire me?)"))
        self.lblRunGame.setText(_translate("CentalWindow", "If you are ready to start the game, please close this window and run the file named \"game.py\"."))
        self.label.setText(_translate("CentalWindow", "DISCLAIMER"))

